"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
class ClassNotFoundError(BaseException):
    def __init__(*args, **kwargs) -> None:
        ...
    


