"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
def split_letters_numbers_brackets(s):
    """
    Split the string into letters, numbers, and brackets (with their content).
    This is a helper function for getting the smallest unique substring, for determining tags.
    """
    ...

def get_smallest_unique_substrings(strings, prefix=...):
    ...

def all_subclasses(cls):
    ...

def get_all_numpy_dtype_strings():
    ...

def get_all_pandas_dtype_strings():
    ...

np_dtypes = ...
pd_dtypes = ...
TYPE_MAP = ...
REVERSE_TYPE_MAP = ...
